ciinabox_version: 0.1

#ciinabox ECS cluster name
cluster_name: ciinabox

#log level - change to :debug to see the AWS commands being executed
log_level: :info

#AWS Availability Zones Idenifers
availability_zones:
  - 'A'
  - 'B'

#change this to your own timezone
timezone: GMT

azId:
  A: 0
  B: 1
  C: 2
  D: 3
  E: 4

# Uncomment below to enable ciinabox environment scheduling
# times are in UTC
# scale_up_schedule: 0 7 * * 1-5
# scale_down_schedule: 0 19 * * *

#Subnet offsets 10.150.x.0/26
vpc:
  SubnetOctetA: "0"
  SubnetOctetB: "1"
ecs:
  SubnetOctetA: "2"
  SubnetOctetB: "3"

#Amazon Linux AMI 2015.03.1 (HVM), SSD Volume Type
natAMI:
  us-east-1:
    ami: ami-60b6c60a
  us-west-2:
    ami: ami-f0091d91
  ap-southeast-2:
    ami: ami-48d38c2b
  eu-west-1:
    ami: ami-bff32ccc

ecs_ami:
  us-east-1:
    ami: ami-cb2305a1
  us-west-2:
    ami: ami-ec75908c
  ap-southeast-2:
    ami: ami-83af8ae0
  eu-west-1:
    ami: ami-13f84d60

#Webhook access only via https
webHooks:
  - 192.30.252.0/22 #github

#extra_stacks:
#  elk:
#    #define template name? - optional
#    file_name: elk
#    parameters:
#      RoleName: search
#      CertName: x
#      StackOctetA: 11
#      StackOctetB: 12
