# ciinabox services default configuration

services:
  - jenkins:
      # Optional Jenkins Service Parameters
      # ContainerImage: base2/ciinabox-jenkins:2.0
      # ContainerMemory: 4096
      # ContainerCPU: 300
      # JAVA_OPTS: -Xmx4096m
      # you only need to add these ports for JNLP slaves
      # LoadBalancerPort: 50000
      # InstancePort: 50000
      # Protocol: TCP

#example for Internal Port for Jenkins
# - jenkins:
#    LoadBalancerPort: 50000
#    InstancePort: 50000
#    Protocol: TCP
# needs internal_elb: true
# will trigger this 2nd hostname for jenkins internal-jenkins.#{dns_domain}
